language: node_js
node_js:
  - '8.11.2'
sudo: required
dist: trusty
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - psql -c 'create database myDiaryTest;' -U postgres
env:
  - Test_URL=postgres://aubjnoxm:qyIs_1Vo-jC9M-060d0NlZ2Vg5nJvJL4@isilo.db.elephantsql.com:5432/aubjnoxm
script: npm run test

after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
cache:
  directories:
    - 'node_modules'
