language: node_js
node_js:
  - '8.11.2'
services:
  - postgresql
before_script:
  - npm install
  - npm install uuid --save


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
